name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Need conda for pymoab install
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Set up conda dependencies
        run: |
          mamba install -y moab

      - name: Install dependencies
        run: |
          python -m pip install ".[dev]"

      - name: Test with pytest
        run: |
          python -m pytest
