name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mambaorg/micromamba:latest
      options: --user=root
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda dependencies
        run: |
          micromamba install -c conda-forge python=${{ matrix.python-version }} moab

      - name: Install dependencies
        run: |
          python -m pip install ".[dev]"

      - name: Test with pytest
        run: |
          python -m pytest
